name: Github-Docker Hub MLOps pipeline - Jenniakato

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.REPO_NAME }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint pytest
          if [ -f my_app/requirements.txt ]; then pip install -r my_app/requirements.txt; fi

      - name: Format
        run: |
          black my_app/app.py

      - name: Lint
        run: |
          pylint --disable=R,C my_app/app.py

      - name: Test
        run: |
          python -m pytest -vv my_app/test.py || echo "No test file found, skipping"

  cd_pipeline:
    runs-on: ubuntu-latest
    needs: [ci_pipeline]

    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build ./my_app -f ./my_app/Dockerfile -t $DOCKER_USER/$REPO_NAME:${{ env.date }}

      - name: Docker push
        run: docker push $DOCKER_USER/$REPO_NAME:${{ env.date }}

